"use client";

import { createContext, useContext, useState, ReactNode, useCallback } from "react";

const translations = {
  en: {
    home: "Home",
    contact: "Contact",
    login: "Log In",
    dashboard: "Dashboard",
    viewMyCV: "View My CV",
    logout: "Log Out",
    content: "Content",
    appearance: "Appearance",
    settings: "Settings",
    personalInfo: "Personal Information",
    personalInfoDesc: "This information will appear at the top of your resume.",
    username: "Username",
    usernameDesc: "URL: /cv/{username}",
    fullName: "Full Name",
    title: "Title",
    email: "Email",
    phone: "Phone",
    website: "Website",
    linkedin: "LinkedIn",
    github: "GitHub",
    summary: "Summary",
    saveSection: "Save Section",
    saving: "Saving...",
    skills: "Skills",
    skillsDesc: "List your technical and professional skills, separated by commas.",
    experience: "Work Experience",
    experienceDesc: "Detail your professional history.",
    addExperience: "Add Experience",
    company: "Company",
    location: "Location",
    startDateEndDate: "Start - End Date",
    description: "Description",
    education: "Education",
    educationDesc: "List your academic background.",
    addEducation: "Add Education",
    degree: "Degree",
    institution: "Institution",
    projects: "Projects",
    projectsDesc: "Showcase your work.",
    addProject: "Add Project",
    projectName: "Project Name",
    url: "URL",
    tags: "Tags (comma-separated)",
    certifications: "Certifications",
    certificationsDesc: "List your certifications.",
    addCertification: "Add Certification",
    certificationName: "Certificate Name",
    issuer: "Issuer",
    date: "Date",
    templateSelection: "Template Selection",
    templateSelectionDesc: "Choose a template for your resume.",
    saveAppearance: "Save Appearance",
    classic: "Classic",
    modern: "Modern",
    minimalist: "Minimalist",
    passwordChange: "Password Change",
    passwordChangeDesc: "Update your password here. You will be logged out after a successful change.",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    updatePassword: "Update Password",
    passwordsDoNotMatch: "Passwords do not match.",
    passwordUpdated: "Password updated successfully. Please log in again.",
    passwordUpdateError: "Password Update Error",
    sectionSaved: "{section} Saved",
    sectionSavedDesc: "Your information has been successfully updated.",
    saveError: "Save Error",
    getInTouch: "Get in Touch",
    getInTouchDesc: "Feel free to reach out for any questions, suggestions, or collaboration proposals.",
    contactInfoTitle: "Contact Information",
    privacy: "Privacy",
    terms: "Terms",
    welcomeBack: "Welcome Back",
    welcomeBackDesc: "Enter your credentials to access your account.",
    password: "Password",
    loggingIn: "Logging in...",
    loginFailed: "Login Failed",
    loginFailedDesc: "Invalid credentials. Please try again.",
    loginSuccess: "Login Successful",
    loginSuccessDesc: "Welcome back! Redirecting you to the dashboard.",
    backToHome: "Back to Home",
    heroTitle: "Craft Your Professional Story",
    heroSubtitle: "Build a stunning, ATS-friendly resume in minutes. Our intuitive editor helps you highlight your skills and experience to land your dream job.",
    heroCtaStart: "Get Started Now",
    heroCtaSample: "View Sample CV",
    featuresTag: "Key Features",
    featuresTitle: "Designed for Success",
    featuresSubtitle: "Everything you need to create a resume that stands out to recruiters and hiring managers.",
    feature1Title: "Intuitive Editor",
    feature1Desc: "Easily input your personal info, experience, education, and skills with our guided forms.",
    feature2Title: "ATS-Friendly",
    feature2Desc: "Our templates are optimized for applicant tracking systems, ensuring your resume gets seen.",
    feature3Title: "PDF Download",
    feature3Desc: "Download a pixel-perfect PDF of your resume to share with potential employers.",
    footerCopyright: "© {currentYear} YourResume. All rights reserved.",
    register: "Register",
    registerTitle: "Create an Account",
    registerDesc: "Enter your details to create a new account.",
    haveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    signUpWithGoogle: "Sign up with Google",
    signInWithGoogle: "Sign in with Google",
    orContinueWith: "Or continue with",
    registrationSuccess: "Registration Successful",
    registrationSuccessDesc: "Your account has been created. Redirecting...",
    registrationFailed: "Registration Failed",
  },
  tr: {
    home: "Anasayfa",
    contact: "İletişim",
    login: "Giriş Yap",
    dashboard: "Pano",
    viewMyCV: "CV'mi Görüntüle",
    logout: "Çıkış Yap",
    content: "İçerik",
    appearance: "Görünüm",
    settings: "Ayarlar",
    personalInfo: "Kişisel Bilgiler",
    personalInfoDesc: "Bu bilgiler özgeçmişinizin en üstünde görünecektir.",
    username: "Kullanıcı Adı",
    usernameDesc: "URL: /cv/{username}",
    fullName: "Tam Adınız",
    title: "Unvan",
    email: "E-posta",
    phone: "Telefon",
    website: "Web Sitesi",
    linkedin: "LinkedIn",
    github: "GitHub",
    summary: "Özet",
    saveSection: "Bölümü Kaydet",
    saving: "Kaydediliyor...",
    skills: "Yetenekler",
    skillsDesc: "Teknik ve profesyonel yeteneklerinizi virgülle ayırarak listeleyin.",
    experience: "İş Deneyimi",
    experienceDesc: "Profesyonel geçmişinizi detaylandırın.",
    addExperience: "Deneyim Ekle",
    company: "Şirket",
    location: "Konum",
    startDateEndDate: "Başlangıç - Bitiş Tarihi",
    description: "Açıklama",
    education: "Eğitim",
    educationDesc: "Akademik geçmişinizi listeleyin.",
    addEducation: "Eğitim Ekle",
    degree: "Bölüm",
    institution: "Kurum",
    projects: "Projeler",
    projectsDesc: "Çalışmalarınızı sergileyin.",
    addProject: "Proje Ekle",
    projectName: "Proje Adı",
    url: "URL",
    tags: "Etiketler (virgülle ayırın)",
    certifications: "Sertifikalar",
    certificationsDesc: "Sahip olduğunuz sertifikaları listeleyin.",
    addCertification: "Sertifika Ekle",
    certificationName: "Sertifika Adı",
    issuer: "Veren Kurum",
    date: "Tarih",
    templateSelection: "Şablon Seçimi",
    templateSelectionDesc: "Özgeçmişiniz için bir şablon seçin.",
    saveAppearance: "Görünümü Kaydet",
    classic: "Klasik",
    modern: "Modern",
    minimalist: "Minimalist",
    passwordChange: "Şifre Değiştirme",
    passwordChangeDesc: "Şifrenizi buradan güncelleyin. Başarılı bir değişiklikten sonra çıkış yapılacaktır.",
    newPassword: "Yeni Şifre",
    confirmNewPassword: "Yeni Şifreyi Onayla",
    updatePassword: "Şifreyi Güncelle",
    passwordsDoNotMatch: "Şifreler eşleşmiyor.",
    passwordUpdated: "Şifre başarıyla güncellendi. Lütfen tekrar giriş yapın.",
    passwordUpdateError: "Şifre Güncelleme Hatası",
    sectionSaved: "{section} Kaydedildi",
    sectionSavedDesc: "Bilgileriniz başarıyla güncellendi.",
    saveError: "Kaydetme Hatası",
    getInTouch: "İletişime Geçin",
    getInTouchDesc: "Sorularınız, önerileriniz veya işbirliği teklifleriniz için bize ulaşmaktan çekinmeyin.",
    contactInfoTitle: "İletişim Bilgileri",
    privacy: "Gizlilik",
    terms: "Koşullar",
    welcomeBack: "Tekrar Hoş Geldiniz",
    welcomeBackDesc: "Hesabınıza erişmek için bilgilerinizi girin.",
    password: "Şifre",
    loggingIn: "Giriş yapılıyor...",
    loginFailed: "Giriş Başarısız",
    loginFailedDesc: "Geçersiz kimlik bilgileri. Lütfen tekrar deneyin.",
    loginSuccess: "Giriş Başarılı",
    loginSuccessDesc: "Tekrar hoş geldiniz! Panoya yönlendiriliyorsunuz.",
    backToHome: "Anasayfaya Dön",
    heroTitle: "Profesyonel Hikayenizi Yaratın",
    heroSubtitle: "Dakikalar içinde göz alıcı, ATS uyumlu bir özgeçmiş oluşturun. Sezgisel düzenleyicimiz, hayalinizdeki işi bulmanız için becerilerinizi ve deneyiminizi vurgulamanıza yardımcı olur.",
    heroCtaStart: "Hemen Başlayın",
    heroCtaSample: "Örnek CV'yi Görüntüle",
    featuresTag: "Ana Özellikler",
    featuresTitle: "Başarı İçin Tasarlandı",
    featuresSubtitle: "İşe alımcıların ve yöneticilerin dikkatini çeken bir özgeçmiş oluşturmak için ihtiyacınız olan her şey.",
    feature1Title: "Sezgisel Düzenleyici",
    feature1Desc: "Kişisel bilgilerinizi, deneyiminizi, eğitiminizi ve becerilerinizi rehberli formlarımızla kolayca girin.",
    feature2Title: "ATS Uyumlu",
    feature2Desc: "Şablonlarımız, başvuru takip sistemleri için optimize edilmiştir ve özgeçmişinizin görülmesini sağlar.",
    feature3Title: "PDF İndirme",
    feature3Desc: "Potansiyel işverenlerle paylaşmak için özgeçmişinizin piksel mükemmelliğinde bir PDF'ini indirin.",
    footerCopyright: "© {currentYear} YourResume. Tüm hakları saklıdır.",
    register: "Kayıt Ol",
    registerTitle: "Hesap Oluştur",
    registerDesc: "Yeni bir hesap oluşturmak için bilgilerinizi girin.",
    haveAccount: "Zaten bir hesabınız var mı?",
    dontHaveAccount: "Hesabınız yok mu?",
    signUpWithGoogle: "Google ile Kaydol",
    signInWithGoogle: "Google ile Giriş Yap",
    orContinueWith: "Veya şununla devam et",
    registrationSuccess: "Kayıt Başarılı",
    registrationSuccessDesc: "Hesabınız oluşturuldu. Yönlendiriliyor...",
    registrationFailed: "Kayıt Başarısız",
  },
};

type Language = keyof typeof translations;
type TranslationKeys = keyof typeof translations['en'];

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKeys, params?: { [key: string]: string }) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = useCallback((key: TranslationKeys, params?: { [key: string]: string }) => {
    let translation = translations[language][key] || translations['en'][key];
    if (params) {
      for (const paramKey in params) {
        translation = translation.replace(`{${paramKey}}`, params[paramKey]);
      }
    }
    return translation;
  }, [language]);

  const value = { language, setLanguage, t };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
