
"use client";

import { createContext, useContext, useState, ReactNode, useCallback } from "react";

const translations = {
  en: {
    home: "Home",
    contact: "Contact",
    login: "Log In",
    dashboard: "Dashboard",
    viewMyCV: "View My CV",
    logout: "Log Out",
    content: "Content",
    appearance: "Appearance",
    settings: "Settings",
    personalInfo: "Personal Information",
    personalInfoDesc: "This information will appear at the top of your resume.",
    username: "Username",
    usernameDesc: "URL: /cv/{username}",
    fullName: "Full Name",
    title: "Title",
    email: "Email",
    phone: "Phone",
    website: "Website",
    linkedin: "LinkedIn",
    github: "GitHub",
    summary: "Summary",
    saveSection: "Save Section",
    saving: "Saving...",
    skills: "Skills",
    skillsDesc: "List your technical and professional skills, separated by commas.",
    experience: "Work Experience",
    experienceDesc: "Detail your professional history.",
    addExperience: "Add Experience",
    company: "Company",
    location: "Location",
    startDateEndDate: "Start - End Date",
    description: "Description",
    education: "Education",
    educationDesc: "List your academic background.",
    addEducation: "Add Education",
    degree: "Degree",
    institution: "Institution",
    projects: "Projects",
    projectsDesc: "Showcase your work.",
    addProject: "Add Project",
    projectName: "Project Name",
    url: "URL",
    tags: "Tags (comma-separated)",
    certifications: "Certifications",
    certificationsDesc: "List your certifications.",
    addCertification: "Add Certification",
    certificationName: "Certificate Name",
    issuer: "Issuer",
    date: "Date",
    templateSelection: "Template Selection",
    templateSelectionDesc: "Choose a template for your resume.",
    saveAppearance: "Save Appearance",
    classic: "Classic",
    modern: "Modern",
    minimalist: "Minimalist",
    twoColumn: "Create Your Own",
    passwordChange: "Password Change",
    passwordChangeDesc: "Update your password here. You will be logged out after a successful change.",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    updatePassword: "Update Password",
    passwordsDoNotMatch: "Passwords do not match.",
    passwordUpdated: "Password updated successfully. Please log in again.",
    passwordUpdateError: "Password Update Error",
    sectionSaved: "{section} Saved",
    sectionSavedDesc: "Your information has been successfully updated.",
    saveError: "Save Error",
    usernameTaken: "This username is already taken.",
    getInTouch: "Get in Touch",
    getInTouchDesc: "Feel free to reach out for any questions, suggestions, or collaboration proposals.",
    contactInfoTitle: "Contact Information",
    privacy: "Privacy",
    terms: "Terms",
    welcomeBack: "Welcome Back",
    welcomeBackDesc: "Enter your credentials to access your account.",
    password: "Password",
    loggingIn: "Logging in...",
    loginFailed: "Login Failed",
    loginFailedDesc: "Invalid credentials. Please try again.",
    loginSuccess: "Login Successful",
    loginSuccessDesc: "Welcome back! Redirecting you to the dashboard.",
    backToHome: "Back to Home",
    heroTitle: "Craft Your Professional Story",
    heroSubtitle: "Build a stunning, ATS-friendly resume in minutes. Our intuitive editor helps you highlight your skills and experience to land your dream job.",
    heroCtaStart: "Get Started Now",
    heroCtaSample: "View Sample CV",
    featuresTag: "Key Features",
    featuresTitle: "Designed for Success",
    featuresSubtitle: "Everything you need to create a resume that stands out to recruiters and hiring managers.",
    feature1Title: "Intuitive Editor",
    feature1Desc: "Easily input your personal info, experience, education, and skills with our guided forms.",
    feature2Title: "ATS-Friendly",
    feature2Desc: "Our templates are optimized for applicant tracking systems, ensuring your resume gets seen.",
    feature3Title: "PDF Download",
    feature3Desc: "Download a pixel-perfect PDF of your resume to share with potential employers.",
    footerCopyright: "© {currentYear} YourResume. All rights reserved.",
    register: "Register",
    registerTitle: "Create an Account",
    registerDesc: "Enter your details to create a new account.",
    haveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    signUpWithGoogle: "Sign up with Google",
    signInWithGoogle: "Sign in with Google",
    orContinueWith: "Or continue with",
    registrationSuccess: "Registration Successful",
    registrationSuccessDesc: "Your account has been created. Redirecting...",
    registrationFailed: "Registration Failed",
    appearanceManager: "Appearance Manager",
    appearanceManagerDesc: "Manage your CV's layout and template from here.",
    baseTemplate: "Base Template",
    modernTemplateWarning: "The 2-column structure of the Modern template is fixed, so section placement cannot be customized in this template.",
    layoutEditor: "Layout Editor",
    layoutEditorDesc: "Customize the structure of your two-column resume.",
    backToDashboard: "Back to Dashboard",
    saveLayout: "Save Layout",
    mainContent: "Main Content",
    sidebar: "Sidebar",
    mainContentEmpty: "Add sections to the main content area.",
    sidebarEmpty: "Add sections to the sidebar.",
    doubleClickToEdit: "Double-click to edit layout.",
    layoutEditorTitleV2: "🛠️ Design Your Resume Freely!",
    layoutEditorDescV3: "You're in full control of your resume layout. Want a clean single-column layout? Simply move all sections to the Main Content area. Prefer a two-column professional style? Split your sections between the main area and sidebar.",
    whatYouCanDo: "What you can do:",
    rearrangeSections: "Rearrange sections using the arrow buttons.",
    chooseLayout: "Create single or two-column layouts.",
    instantPreview: "See an instant preview of your changes on your CV page.",
    likeCanva: "🎨 It’s like designing your CV: Flexible, visual, and personal.",
    saveReminder: "✅ When you're done customizing, don't forget to click Save Layout!",
  },
  tr: {
    home: "Anasayfa",
    contact: "İletişim",
    login: "Giriş Yap",
    dashboard: "Pano",
    viewMyCV: "CV'mi Görüntüle",
    logout: "Çıkış Yap",
    content: "İçerik",
    appearance: "Görünüm",
    settings: "Ayarlar",
    personalInfo: "Kişisel Bilgiler",
    personalInfoDesc: "Bu bilgiler özgeçmişinizin en üstünde görünecektir.",
    username: "Kullanıcı Adı",
    usernameDesc: "URL: /cv/{username}",
    fullName: "Ad Soyad",
    title: "Unvan",
    email: "E-posta",
    phone: "Telefon",
    website: "Web Sitesi",
    linkedin: "LinkedIn",
    github: "GitHub",
    summary: "Özet",
    saveSection: "Bölümü Kaydet",
    saving: "Kaydediliyor...",
    skills: "Yetenekler",
    skillsDesc: "Teknik ve profesyonel yeteneklerinizi virgülle ayırarak listeleyin.",
    experience: "İş Deneyimi",
    experienceDesc: "Profesyonel geçmişinizi detaylandırın.",
    addExperience: "Deneyim Ekle",
    company: "Şirket",
    location: "Konum",
    startDateEndDate: "Başlangıç - Bitiş Tarihi",
    description: "Açıklama",
    education: "Eğitim",
    educationDesc: "Akademik geçmişinizi listeleyin.",
    addEducation: "Eğitim Ekle",
    degree: "Bölüm",
    institution: "Kurum",
    projects: "Projeler",
    projectsDesc: "Çalışmalarınızı sergileyin.",
    addProject: "Proje Ekle",
    projectName: "Proje Adı",
    url: "URL",
    tags: "Etiketler (virgülle ayırın)",
    certifications: "Sertifikalar",
    certificationsDesc: "Sahip olduğunuz sertifikaları listeleyin.",
    addCertification: "Sertifika Ekle",
    certificationName: "Sertifika Adı",
    issuer: "Veren Kurum",
    date: "Tarih",
    templateSelection: "Şablon Seçimi",
    templateSelectionDesc: "Özgeçmişiniz için bir şablon seçin.",
    saveAppearance: "Görünümü Kaydet",
    classic: "Klasik",
    modern: "Modern",
    minimalist: "Minimalist",
    twoColumn: "Kendin Oluştur",
    passwordChange: "Şifre Değiştirme",
    passwordChangeDesc: "Şifrenizi buradan güncelleyin. Başarılı bir değişiklikten sonra çıkış yapılacaktır.",
    newPassword: "Yeni Şifre",
    confirmNewPassword: "Yeni Şifreyi Onayla",
    updatePassword: "Şifreyi Güncelle",
    passwordsDoNotMatch: "Şifreler eşleşmiyor.",
    passwordUpdated: "Şifre başarıyla güncellendi. Lütfen tekrar giriş yapın.",
    passwordUpdateError: "Şifre Güncelleme Hatası",
    sectionSaved: "{section} Kaydedildi",
    sectionSavedDesc: "Bilgileriniz başarıyla güncellendi.",
    saveError: "Kaydetme Hatası",
    usernameTaken: "Bu kullanıcı adı zaten alınmış.",
    getInTouch: "İletişime Geçin",
    getInTouchDesc: "Sorularınız, önerileriniz veya işbirliği teklifleriniz için bize ulaşmaktan çekinmeyin.",
    contactInfoTitle: "İletişim Bilgileri",
    privacy: "Gizlilik",
    terms: "Koşullar",
    welcomeBack: "Tekrar Hoş Geldiniz",
    welcomeBackDesc: "Hesabınıza erişmek için bilgilerinizi girin.",
    password: "Şifre",
    loggingIn: "Giriş yapılıyor...",
    loginFailed: "Giriş Başarısız",
    loginFailedDesc: "Geçersiz kimlik bilgileri. Lütfen tekrar deneyin.",
    loginSuccess: "Giriş Başarılı",
    loginSuccessDesc: "Tekrar hoş geldiniz! Panoya yönlendiriliyorsunuz.",
    backToHome: "Anasayfaya Dön",
    heroTitle: "Profesyonel Hikayenizi Yaratın",
    heroSubtitle: "Dakikalar içinde göz alıcı, ATS uyumlu bir özgeçmiş oluşturun. Sezgisel düzenleyicimiz, hayalinizdeki işi bulmanız için becerilerinizi ve deneyiminizi vurgulamanıza yardımcı olur.",
    heroCtaStart: "Hemen Başlayın",
    heroCtaSample: "Örnek CV'yi Görüntüle",
    featuresTag: "Ana Özellikler",
    featuresTitle: "Başarı İçin Tasarlandı",
    featuresSubtitle: "İşe alımcıların ve yöneticilerin dikkatini çeken bir özgeçmiş oluşturmak için ihtiyacınız olan her şey.",
    feature1Title: "Sezgisel Düzenleyici",
    feature1Desc: "Kişisel bilgilerinizi, deneyiminizi, eğitiminizi ve becerilerinizi rehberli formlarımızla kolayca girin.",
    feature2Title: "ATS Uyumlu",
    feature2Desc: "Şablonlarımız, başvuru takip sistemleri için optimize edilmiştir ve özgeçmişinizin görülmesini sağlar.",
    feature3Title: "PDF İndirme",
    feature3Desc: "Potansiyel işverenlerle paylaşmak için özgeçmişinizin piksel mükemmelliğinde bir PDF'ini indirin.",
    footerCopyright: "© {currentYear} YourResume. Tüm hakları saklıdır.",
    register: "Kayıt Ol",
    registerTitle: "Hesap Oluştur",
    registerDesc: "Yeni bir hesap oluşturmak için bilgilerinizi girin.",
    haveAccount: "Zaten bir hesabınız var mı?",
    dontHaveAccount: "Hesabınız yok mu?",
    signUpWithGoogle: "Google ile Kaydol",
    signInWithGoogle: "Google ile Giriş Yap",
    orContinueWith: "Veya şununla devam et",
    registrationSuccess: "Kayıt Başarılı",
    registrationSuccessDesc: "Hesabınız oluşturuldu. Yönlendiriliyor...",
    registrationFailed: "Kayıt Başarısız",
    appearanceManager: "Görünüm Yöneticisi",
    appearanceManagerDesc: "CV'nizin düzenini ve şablonunu buradan yönetin.",
    baseTemplate: "Temel Şablon",
    modernTemplateWarning: "Modern şablonun 2 sütunlu yapısı sabittir, bu nedenle bölüm yerleşimi bu şablonda özelleştirilemez.",
    layoutEditor: "Yerleşim Düzeni Editörü",
    layoutEditorDesc: "İki sütunlu özgeçmişinizin yapısını özelleştirin.",
    backToDashboard: "Panoya Geri Dön",
    saveLayout: "Düzeni Kaydet",
    mainContent: "Ana İçerik",
    sidebar: "Kenar Çubuğu",
    mainContentEmpty: "Ana içerik alanına bölüm ekleyin.",
    sidebarEmpty: "Kenar çubuğuna bölüm ekleyin.",
    doubleClickToEdit: "Düzeni düzenlemek için çift tıklayın.",
    layoutEditorTitleV2: "🛠️ Özgeçmişini Özgürce Tasarla!",
    layoutEditorDescV3: "Özgeçmiş düzenin tamamen senin kontrolünde. Sade, tek sütunlu bir düzen mi istiyorsun? Tüm bölümleri Ana İçerik alanına taşı. Profesyonel, iki sütunlu bir stil mi tercih ediyorsun? Bölümlerini ana alan ve kenar çubuğu arasında böl.",
    whatYouCanDo: "Neler yapabilirsin:",
    rearrangeSections: "Ok düğmelerini kullanarak bölümleri yeniden düzenle.",
    chooseLayout: "Tek veya iki sütunlu düzenler oluştur.",
    instantPreview: "Yaptığın değişikliklerin önizlemesini CV sayfanızda anında gör.",
    likeCanva: "🎨 Tıpkı kendi CV'ni tasarlamak gibi: Esnek, görsel ve kişisel.",
    saveReminder: "✅ Özelleştirmeyi bitirdiğinde, Düzeni Kaydet'e tıklamayı unutma!",
  },
};

type Language = keyof typeof translations;
type TranslationKeys = keyof typeof translations['en'];

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKeys, params?: { [key: string]: string }) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = useCallback((key: TranslationKeys, params?: { [key: string]: string }) => {
    let translation = translations[language][key] || translations['en'][key];
    if (params) {
      for (const paramKey in params) {
        translation = translation.replace(`{${paramKey}}`, params[paramKey]);
      }
    }
    return translation;
  }, [language]);

  const value = { language, setLanguage, t };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
